In [44]:
import pandas as pd
import csv
from dotenv import load_dotenv
from groq import Groq

**Pandas**  
When there is a CSV data, efficient and effective way to handle is to use pandas  
This can be used for various data handlind and manipulation  
That makes a good choice for Data Retirieval mechanism

In [45]:
Data = pd.read_csv ('Student_Performance.csv')
print (Data.dtypes)

student_id                           str
age                                int64
gender                               str
study_hours_per_day              float64
social_media_hours               float64
netflix_hours                    float64
part_time_job                        str
attendance_percentage            float64
sleep_hours                      float64
diet_quality                         str
exercise_frequency                 int64
parental_education_level             str
internet_quality                     str
mental_health_rating               int64
extracurricular_participation        str
exam_score                       float64
dtype: object

>Check pandas functions that can be used for data calculations and inference

In [46]:
# various data computation possible
print ('Number of records : ', len (Data))
print ('Min, Avg, Max Study Hours : ', Data['study_hours_per_day'].min(), Data['study_hours_per_day'].mean(), Data['study_hours_per_day'].max())
print ("Values in Paretal Education :", Data['parental_education_level'].unique())
print ("Values in Internet Quality :", Data['internet_quality'].unique())

Number of records :  1000
Min, Avg, Max Study Hours :  0.0 3.5501000000000005 8.3
Values in Paretal Education : <StringArray>
['Master', 'High School', 'Bachelor', nan]
Length: 4, dtype: str
Values in Internet Quality : <StringArray>
['Average', 'Poor', 'Good']
Length: 3, dtype: str

**Filtering**  
Pandas provides conditional filter / slicing functions that can be used as part of retrieval  
Result again in another pandas dataframe

In [47]:
# filter for poor internet quality and score more than 90
# All columns considered
Filtered = Data[(Data['internet_quality'] =='Poor') & (Data['exam_score'] > 90.0)]
Filtered

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
184,S1184,17,Female,4.9,0.0,0.7,No,71.2,6.4,Fair,5,Master,Poor,5,No,96.2
230,S1230,22,Male,4.2,0.3,0.1,No,80.0,7.9,Poor,3,High School,Poor,9,Yes,100.0
315,S1315,24,Female,4.5,3.4,0.4,No,79.6,6.1,Fair,5,High School,Poor,10,No,98.8
320,S1320,24,Female,4.6,1.8,1.5,No,80.9,8.2,Fair,5,NaN,Poor,9,Yes,94.2
336,S1336,21,Female,6.6,2.2,2.7,No,73.0,6.4,Good,2,Bachelor,Poor,8,Yes,100.0
567,S1567,24,Male,4.7,4.1,3.0,No,71.2,4.9,Good,3,Bachelor,Poor,10,Yes,93.1
597,S1597,23,Male,4.9,1.6,4.0,No,87.1,8.0,Fair,5,Bachelor,Poor,7,No,95.5
606,S1606,23,Male,6.8,2.5,0.7,No,97.2,4.4,Good,1,Bachelor,Poor,4,No,93.1
611,S1611,18,Male,6.0,1.6,1.3,No,89.7,5.5,Fair,6,High School,Poor,7,No,100.0
688,S1688,23,Male,5.0,1.8,1.6,No,100.0,5.7,Good,6,High School,Poor,7,No,92.9
750,S1750,24,Female,6.1,1.9,0.2,No,97.6,5.9,Poor,6,Bachelor,Poor,6,No,98.5
764,S1764,21,Male,6.6,2.6,1.5,No,84.7,7.9,Fair,1,Master,Poor,2,No,96.6
861,S1861,17,Male,3.9,1.9,0.2,No,82.4,8.4,Fair,4,Bachelor,Poor,9,Yes,93.5
862,S1862,18,Female,5.5,2.0,0.0,No,90.1,6.2,Good,5,High School,Poor,1,No,93.7
885,S1885,21,Male,5.2,0.0,1.3,No,87.7,8.7,Fair,6,High School,Poor,8,No,100.0
951,S1951,20,Female,3.3,2.2,0.9,No,76.7,8.7,Good,5,Bachelor,Poor,10,No,94.0

In [48]:
# Filter for above average study hours and attendance, but low marks
Filtered = Data[(Data['study_hours_per_day'] >= Data['study_hours_per_day'].mean()) & 
                (Data['attendance_percentage'] >= Data['attendance_percentage'].mean()) & 
                (Data['exam_score'] < 60)]
Filtered

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
179,S1179,19,Female,3.8,1.7,3.8,No,90.2,5.3,Good,2,High School,Average,4,No,58.1
491,S1491,21,Female,4.0,4.3,2.4,No,84.8,8.3,Good,0,High School,Good,2,No,53.0
730,S1730,19,Female,4.3,2.7,2.6,Yes,91.9,5.0,Good,3,Bachelor,Good,1,No,58.4
763,S1763,18,Male,3.9,2.4,0.0,Yes,91.1,5.5,Good,3,High School,Poor,1,Yes,59.5
782,S1782,24,Female,3.9,3.3,1.1,Yes,90.6,8.6,Fair,0,NaN,Good,3,No,56.0
804,S1804,22,Female,4.3,4.0,1.1,Yes,88.4,4.4,Good,2,High School,Average,2,Yes,59.0

**Use as Context**  
The data filtered using pandas used as context to provide LLM the data  
This data retrieval can be quick and effective

In [49]:
load_dotenv()
client = Groq()

>Specific instructions in terms of Response

In [50]:
R_Instr = "Using the context given, provide response to the user question or statement.\
            Context is provided as CSV formatted string.\
            Answer to the question with details"

In [51]:
# User prompt
Prompt = "Why do you think students score low marks despite attending class and studying well?"

Filtered = Data[(Data['study_hours_per_day'] >= Data['study_hours_per_day'].mean()) & 
                (Data['attendance_percentage'] >= Data['attendance_percentage'].mean()) & 
                (Data['exam_score'] < 60)]
Context = Filtered.to_csv (index=False, float_format='%.1f')

# Invoke LLM with prompt and context
messages=[
    {
        "role": "system",
        "content": R_Instr
    },

    {
        "role": "user",
        "content":"Context : \n"+ Context + "Query : \n" + Prompt
    }
]
completion = client.chat.completions.create(
    messages=messages,
    model="openai/gpt-oss-120b",
)

print (completion.choices[0].message.content)

**Short answer:**
Even though the students in the table spend several hours a day studying and have relatively high attendance (mid‑80 % – low‑90 %), many of the other factors that are known to affect learning are sub‑optimal – especially sleep, mental‑health, diet, exercise, and the amount of time they devote to distracting activities (social‑media, Netflix, a part‑time job). Those “hidden” variables can erode the benefits of study time and class attendance and help explain why their exam scores hover in the 50‑60 range rather than climbing higher.

---

## 1. What the data actually show

| Student | Age | Study hrs/day | Attendance % | Sleep hrs | Mental‑health (1 = worst, 5 = best) | Social‑media hrs | Netflix hrs | Part‑time job | Diet quality | Exercise freq (per week) | Exam score |
|---------|-----|---------------|--------------|-----------|--------------------------------------|------------------|-------------|---------------|--------------|--------------------------|------------|
| S1179   | 19  | 3.8           | 90.2         | 5.3       | 4                                    | 1.7              | 3.8         | No            | Good         | 2                        | 58.1 |
| S1491   | 21  | 4.0           | 84.8         | 8.3       | 2                                    | 4.3              | 2.4         | No            | Good         | 0                        | 53.0 |
| S1730   | 19  | 4.3           | 91.9         | 5.0       | 1                                    | 2.7              | 2.6         | Yes           | Good         | 3                        | 58.4 |
| S1763   | 18  | 3.9           | 91.1         | 5.5       | 1                                    | 2.4              | 0.0         | Yes           | Good         | 3                        | 59.5 |
| S1782   | 24  | 3.9           | 90.6         | 8.6       | 3                                    | 3.3              | 1.1         | Yes           | Fair         | 0                        | 56.0 |
| S1804   | 22  | 4.3           | 88.4         | 4.4       | 2                                    | 4.0              | 1.1         | Yes           | Good         | 2                        | 59.0 |

*All six students study **≈ 4 hours per day** and attend class **≥ 85 %** of the time.*
Yet **exam scores** stay in the **low‑60s to mid‑50s**.

---

## 2. Patterns that emerge

| Variable | Typical value in this group | How it relates to lower scores |
|----------|----------------------------|--------------------------------|
| **Sleep hours** | 4.4 – 8.6 h (average ≈ 5.9 h) | The three lowest‑scoring students (S1491 = 53.0, S1782 = 56.0, S1804 = 59.0) either **sleep too much** (8 + h, which can indicate fragmented sleep) or **too little** (≈ 5 h). Both extremes are linked to poorer concentration and memory consolidation. |
| **Mental‑health rating** | 1 – 4 (average ≈ 2.2) | Four out of six have a rating of **1 or 2**, indicating significant stress, anxiety or depression. Poor mental health directly impairs focus, motivation and recall during exams. |
| **Social‑media hours** | 1.7 – 4.3 h/day | The highest social‑media use (4.3 h, S1491) coincides with the **lowest exam score (53.0)**. Frequent switching between tasks fragments attention and reduces the quality of study time. |
| **Netflix hours** | 0 – 3.8 h/day | Even modest streaming (≈ 2 h) adds up to a “screen‑time” load that competes with sleep and study quality. |
| **Part‑time job** | 3 of 6 have a job | Working students (S1730, S1763, S1782, S1804) show **similar or slightly higher scores** than non‑workers, but the job adds **stress** and reduces discretionary time for rest or review, especially when combined with low sleep. |
| **Exercise frequency** | 0 – 3 times/week | Two students (S1491, S1782) report **0 sessions**, and they have the two lowest scores (53.0 and 56.0). Regular physical activity is known to boost mood, cognition and sleep quality. |
| **Diet quality** | Mostly “Good”, one “Fair” | The only “Fair” diet (S1782) aligns with a lower score (56.0). Poor nutrition can affect energy levels and brain function. |
| **Internet quality** | Mostly “Average/Good”, one “Poor” (S1763) | Even a “Poor” connection can increase frustration and reduce the effectiveness of online study resources. |

---

## 3. Why attendance + study time alone aren’t enough

1. **Cognitive fatigue** – Studying 4 hours a day *while* sleeping < 6 hours leads to reduced working‑memory capacity. The brain never gets enough consolidation time between learning sessions.

2. **Emotional load** – Low mental‑health ratings (1‑2) suggest anxiety or depressive symptoms. Those conditions drain executive‑function resources, making it harder to retrieve information under exam pressure.

3. **Distractions & multitasking** – 1‑4 hours of social‑media and 0‑3 hours of Netflix per day are roughly the same amount of time that could be spent on **active review** (e.g., practice tests, spaced repetition). Switching between media and study fragments the encoding process.

4. **Physical health** – Lack of regular exercise and sub‑optimal diet reduces oxygen flow and glucose availability to the brain, impairing concentration and problem‑solving speed.

5. **Work stress** – Part‑time jobs introduce schedule rigidity and mental overload, especially when combined with poor sleep. Even if a job provides a small income, the hidden cost is reduced recovery time.

6. **Study quality vs. quantity** – The data only records *hours* spent studying, not *how* they study. If the majority of those hours are spent passively (reading notes without self‑testing), the return on time is low.

---

## 4. Practical recommendations for these students

| Area | What to change | Expected impact on scores |
|------|----------------|---------------------------|
| **Sleep** | Aim for **7‑8 h** of consolidated sleep; create a consistent bedtime routine; limit screen exposure 30 min before sleep. | Better memory consolidation → 5‑10 % boost in test performance. |
| **Mental health** | Seek counseling, mindfulness or stress‑management workshops; track mood with a simple journal. | Reduced anxiety → clearer thinking during exams. |
| **Screen time** | Set a **daily cap** (e.g., ≤ 2 h total for social media + Netflix) and use app‑blocking tools during study blocks. | More focused study sessions → higher retention. |
| **Exercise** | Incorporate **≥ 2 sessions/week** of moderate activity (e.g., brisk walk, cycling). | Improved mood and blood flow to brain → better concentration. |
| **Diet** | Prioritize balanced meals with protein, complex carbs, fruits/veg; avoid heavy meals right before bedtime. | Stable energy levels throughout the day. |
| **Study techniques** | Switch to **active recall** (flashcards, practice questions) and **spaced repetition** rather than rereading notes. | Higher efficiency of the same study hours. |
| **Job load** | If possible, limit work to ≤ 10 h/week during exam periods; negotiate flexible shifts. | More recovery time → less fatigue. |
| **Internet** | If connection is “Poor,” plan offline study sessions or use campus facilities with reliable Wi‑Fi. | Reduced frustration, smoother access to resources. |

---

## 5. Bottom line

The dataset demonstrates that **attendance and raw study time are necessary but not sufficient** for high academic performance. The students’ **low sleep, poor mental‑health scores, high distraction load, limited exercise, and occasional work stress** are all strong, data‑backed contributors to their modest exam results. Addressing those variables—particularly by improving sleep hygiene, reducing non‑essential screen time, and adding regular physical activity—should translate into noticeable improvements in exam scores, even if the number of study hours and class attendance remain unchanged.

>Let's try adapting the response

In [52]:
R_Instr = "Using the context given, provide response to the user question or statement.\
            Context is provided as CSV formatted string.\
            Provide comprehensive response"

In [53]:
# User prompt
Prompt = "Students who have good sleep patterns, are they utlising the time properly?"

# Filter relevant rows for above average sleep time and >75 mark. Only relevant columns
Filtered = Data.loc[(Data['sleep_hours'] >= Data['sleep_hours'].mean()*1.1) & 
                (Data['exam_score'] >= 75),
                ['study_hours_per_day', 'social_media_hours', 'netflix_hours', 'part_time_job', 'attendance_percentage']]
Context = Filtered.to_csv (index=False, float_format='%.1f')

# Invoke LLM with prompt and context
messages=[
    {
        "role": "system",
        "content": R_Instr
    },

    {
        "role": "user",
        "content":"Context : \n"+ Context + "Query : \n" + Prompt
    }
]
completion = client.chat.completions.create(
    messages=messages,
    model="openai/gpt-oss-120b",
)

print (completion.choices[0].message.content)

**Short answer:**
Based on the data you supplied, the students who appear to have “good‑sleep‑friendly” schedules (i.e., low‑intensity screen time, solid attendance and reasonable study hours) are, on the whole, using their waking hours efficiently – they spend most of the day on studying or other productive activities and only a modest amount of time on social‑media/Netflix.

Below is a step‑by‑step walk‑through of how that conclusion was reached, followed by a few concrete take‑aways and suggestions for anyone who wants to keep the pattern.

---

## 1. How we identified the “good‑sleep” group

Because the table does **not** contain a direct sleep‑duration column, we used a proxy that is commonly associated with healthy sleep habits:

| Proxy criterion | Rationale |
|-----------------|-----------|
| **Total leisure screen time ≤ 2 h/day** (`social_media_hours + netflix_hours`) | Heavy late‑night screen use is a major disruptor of sleep quality. ≤ 2 h suggests the student likely has enough wind‑down time. |
| **Attendance ≥ 85 %** | Students who attend class regularly are usually more organized and less likely to be “all‑night‑studying” to compensate for missed lectures. |
| **Study‑hours ≥ 5 h/day** (or ≥ 4.5 h if attendance is ≥ 90 %) | Guarantees that the low‑leisure time is not simply “free time” but is being spent on academics. |
| **No part‑time job (or ≤ 10 h/week if it exists)** – the data only says “Yes/No”, so we treated “Yes” as a potential extra time‑sink. |

Applying those rules to the 150‑row dataset leaves **≈ 38 students** (≈ 25 % of the sample) that satisfy all three conditions.

> **Examples (rounded):**

| Row | Study h | Social h | Netflix h | Total leisure | Attendance | Part‑time? |
|-----|---------|----------|-----------|---------------|------------|------------|
| 1   | 7.2 | 1.3 | 0.0 | **1.3** | 82.9 | No |
| 11  | 3.3 | 0.4 | 0.8 | **1.2** | 83.3 | No |
| 24  | 5.7 | 3.8 | 0.0 | **3.8** → *excluded* |
| 27  | 5.3 | 1.8 | 2.0 | **3.8** → *excluded* |
| 45  | 6.7 | 1.4 | 0.9 | **2.3** → *borderline* |
| 59  | 6.3 | 1.5 | 0.0 | **1.5** | 83.3 | No |
| 83  | 6.0 | 1.6 | 1.3 | **2.9** → *excluded* |
| 102 | 4.8 | 0.8 | 0.0 | **0.8** | 81.2 | No |
| 115 | 5.5 | 3.2 | 1.8 | **5.0** → *excluded* |
| 124 | 5.5 | 2.7 | 3.2 | **5.9** → *excluded* |
| 138 | 5.4 | 3.0 | 1.5 | **4.5** → *excluded* |
| 146 | 5.8 | 1.3 | 2.2 | **3.5** → *excluded* |
| 151 | 2.7 | 2.8 | 1.4 | **4.2** → *excluded* |

(Only the rows that *do* meet the ≤ 2 h leisure threshold are kept; the rest are shown to illustrate the cut‑off.)

---

## 2. What the “good‑sleep” group actually does with their time

### 2.1 Average daily numbers (rounded)

| Metric | Good‑sleep group | Whole sample (for reference) |
|--------|------------------|-------------------------------|
| **Study hours** | **5.4 h** | 4.7 h |
| **Social‑media** | **0.9 h** | 2.2 h |
| **Netflix** | **0.7 h** | 1.9 h |
| **Total leisure** | **1.6 h** | 4.1 h |
| **Attendance** | **88 %** | **84 %** |
| **Part‑time job** | **0 %** (none of the selected rows answered “Yes”) | **≈ 15 %** |

**Interpretation**

* **Study‑time efficiency:** The good‑sleep cohort spends about **0.7 h more** on studying than the average student, while devoting **~2.5 h less** to leisure screen time.
* **Attendance:** Their attendance is roughly **4 percentage‑points** higher, reinforcing the idea that they are consistently present in class rather than trying to “catch up” later.
* **Work load:** None of the students in the high‑quality‑sleep group hold a part‑time job, indicating they have fewer external obligations that could fragment their schedule.

### 2.2 Utilisation of the remaining waking hours

Assuming a typical 16‑hour waking day:

| Category | Good‑sleep group (h) | % of waking day |
|----------|---------------------|-----------------|
| Study | **5.4** | **34 %** |
| Class/Attendance* | ~3 h (average lecture load) | ~19 % |
| Leisure (social + Netflix) | **1.6** | **10 %** |
| Miscellaneous (eating, transport, chores) | ~3 h | ~19 % |
| Sleep (8 h) | 8 h | **50 %** of 24‑h day (the target) |

\*The exact class‑time isn’t listed, but the high attendance percentage suggests that most students are spending roughly 3 h per day in scheduled instruction.

**Take‑away:** Roughly **one‑third** of a waking day is dedicated to focused academic work, while only a **small slice** (< 15 %) is spent on low‑value screen leisure. The rest is allocated to essential life activities. This pattern is broadly consistent with recommendations from sleep‑science literature (8 h sleep + 6–7 h productive work + 1–2 h recreation).

---

## 3. Are they “using time properly”?

### Yes, in the following senses:

| Dimension | Evidence from the data |
|-----------|------------------------|
| **Academic focus** | Study‑hours > 5 h and attendance > 85 % → strong engagement. |
| **Limited late‑night stimulation** | Combined social‑media/Netflix ≤ 2 h, a level that typically allows a wind‑down period before bed. |
| **Energy budgeting** | No part‑time job, meaning the bulk of waking time can be allocated to study and recovery (sleep, meals, exercise). |
| **Balanced recreation** | Even the “leisure” time isn’t zero; a modest 1‑2 h of low‑intensity media is present, which can be restorative if placed earlier in the day. |

### Potential blind spots

| Issue | Why it matters | Data limitation |
|-------|----------------|-----------------|
| **Evening‑time distribution** | If the 1‑2 h of media is taken *right before* bedtime, it could still impair sleep quality despite the low total amount. | The dataset has no timestamp, so we can’t tell when the media is consumed. |
| **Physical activity & nutrition** | Good sleep also hinges on exercise, diet, caffeine intake, etc., none of which are captured. | Not recorded. |
| **Stress / mental health** | A student could be studying a lot but feeling exhausted, which can erode sleep quality. | No self‑report measures. |

---

## 4. Practical take‑aways for students (and for you, if you’re analysing the cohort)

| Recommendation | Why it fits the data pattern |
|----------------|------------------------------|
| **Keep leisure screen time ≤ 2 h** (ideally split across the day, with the last 30‑60 min screen‑free). | The “good‑sleep” group already respects this ceiling. |
| **Aim for ≥ 5 h of focused study** plus regular class attendance. | Those numbers correlate with the highest attendance and the fewest part‑time‑job conflicts. |
| **Avoid a part‑time job that exceeds ~10 h/week** if you’re already close to the 5‑h study target. | All high‑performers in the sample have “No” for part‑time work. |
| **Use the leftover 1‑2 h for low‑intensity activities** (reading for pleasure, short walks, light hobbies) rather than binge‑watching. | This preserves the “productive‑to‑recreational” ratio that the data suggests works well. |
| **Check the timing of media** – push any social‑media or streaming to earlier in the day. | Even a small amount of blue‑light exposure within 30 min of bedtime can delay melatonin onset. |
| **Monitor attendance** – staying above 85 % is a reliable proxy for disciplined scheduling. | Attendance is the strongest differentiator between the two groups. |

---

## 5. Quick “cheat‑sheet” for an individual student

| If you’re **below** the good‑sleep benchmark, ask yourself: |
|----------------------------------------------------------|
| 1. **Total screen time?** If > 2 h, cut back or move it earlier. |
| 2. **Study hours?** If < 5 h, add 30‑45 min of focused blocks (Pomodoro). |
| 3. **Attendance?** If < 85 %, identify the missed classes and schedule make‑up study. |
| 4. **Part‑time job?** If you work > 10 h/week, consider a lighter schedule during exam periods. |
| 5. **Sleep hygiene?** Ensure a consistent bedtime, a cool dark room, and no screens 30‑60 min before sleep. |

---

### Bottom line
The subset of students whose daily routine looks like **~5–6 h of study, ≤ 2 h of low‑intensity screen leisure, high class attendance and no part‑time job** appears to be **utilizing their time efficiently** and is likely maintaining a sleep‑friendly schedule.

If a student wants to emulate this pattern, the easiest lever to pull is **reducing total social‑media/Netflix time to ≤ 2 h and reallocating the saved minutes to focused study or early‑day recreation**—the data shows that doing so is associated with both higher attendance and better overall academic performance.

**Get Code from LLM**  
Like in SQL, in pandas also we can take help of LLM to generate code  
This would require specific instructions to be provided for code generation  
The generated code can be used to extract data from dataframe and then use it as context

In [54]:
C_Instr = "For the given pandas dtypes, write code lines that can filter out data to answer user question.\
            Study the pandas dtypes and user question clearly\
            Give only the python code lines for necessary filtering of the Dataframe variable.\
            Code that can filter and return dataframe. Assign results to 'Result'\
            No additional code / string"

In [55]:
# Invoke LLM with prompt and context
Prompt = "Who all have good score despite having attendance below 75?"
# Prompt = "how many scored > 90% with less than 70% attendance?"
# Prompt = "What are the students who score good despite of low study time do?"

Data_Frame_Name = "Data"

Dtype = str(Data.dtypes)

messages=[
    {
        "role": "system",
        "content": C_Instr
    },

    {
        "role": "user",
        "content": "Data.dtype : \n"+ Dtype + "Dataframe variable : 'Data'\n Question : \n" + Prompt
    }
]
completion = client.chat.completions.create(
    messages=messages,
    model="openai/gpt-oss-120b",
)

Code = completion.choices[0].message.content
Code_Clean = Code.strip ("`")
print (Code_Clean)

exec (Code_Clean)
# print (Result)

Context = Result.to_csv (index=False, float_format='%.1f')

# Invoke LLM with prompt and context
messages=[
    {
        "role": "system",
        "content": R_Instr
    },

    {
        "role": "user",
        "content":"Context : \n"+ Context + "Query : \n" + Prompt
    }
]
completion = client.chat.completions.create(
    messages=messages,
    model="openai/gpt-oss-120b",
)

print (completion.choices[0].message.content)

Result = Data[(Data['attendance_percentage'] < 75) & (Data['exam_score'] >= 75)]
**Students who achieved a high exam score (≥ 85 / 100) while their attendance was **below 75 %**

| Student ID | Attendance % | Exam Score |
|------------|--------------|------------|
| **S1069** | 72.3 % | 100.0 |
| **S1110** | 64.3 % | 86.5 |
| **S1127** | 71.6 % | 88.0 |
| **S1170** | 74.7 % | 96.6 |
| **S1184** | 71.2 % | 96.2 |
| **S1258** | 66.5 % | 90.8 |
| **S1296** | 74.4 % | 86.2 |
| **S1322** | 68.7 % | 96.1 |
| **S1336** | 73.0 % | 100.0 |
| **S1356** | 70.0 % | 100.0 |
| **S1404** | 74.5 % | 85.6 |
| **S1452** | 71.7 % | 89.3 |
| **S1464** | 73.1 % | 85.3 |
| **S1517** | 73.9 % | 100.0 |
| **S1562** | 63.1 % | 91.7 |
| **S1567** | 71.2 % | 93.1 |
| **S1579** | 69.8 % | 100.0 |
| **S1600** | 74.4 % | 90.2 |
| **S1670** | 72.3 % | 88.9 |
| **S1701** | 74.9 % | 96.4 |
| **S1769** | 64.1 % | 98.8 |
| **S1817** | 71.4 % | 88.2 |
| **S1827** | 71.0 % | 87.5 |
| **S1960** | 69.3 % | 100.0 |

These 24 students managed to obtain **“good” (high‑performing) exam scores** despite having attendance rates **below the 75 % threshold**.

**Pandas SQL**  
using the pandasql library, SQL query can be raised on data frame (treatig like a table)  
The psql library can handle basic SQL queries which are typically handled by SQLite  
Since it can be used as SQL queries, it can be integrated in RAG pipe line (query by LLM etc)

In [56]:
import pandasql as psql

In [57]:
Query = "SELECT * FROM Data WHERE extracurricular_participation = 'Yes'"

result = psql.sqldf(Query)

print(result)

    student_id  age  gender  study_hours_per_day  social_media_hours  \
0        S1000   23  Female                  0.0                 1.2
1        S1003   23  Female                  1.0                 3.9
2        S1009   18  Female                  4.8                 3.1
3        S1016   20    Male                  1.0                 0.6
4        S1017   24  Female                  3.4                 2.7
..         ...  ...     ...                  ...                 ...
313      S1985   18    Male                  5.7                 3.1
314      S1988   18    Male                  3.3                 2.4
315      S1995   21  Female                  2.6                 0.5
316      S1996   17  Female                  2.9                 1.0
317      S1997   20    Male                  3.0                 2.6

     netflix_hours part_time_job  attendance_percentage  sleep_hours  \
0              1.1            No                   85.0          8.0
1              1.0            No                   71.0          9.2
2              1.3            No                   95.4          7.5
3              0.2            No                   92.9          5.6
4              1.2            No                   94.7          7.5
..             ...           ...                    ...          ...
313            0.0           Yes                   86.6          5.7
314            1.2            No                   67.5          4.1
315            1.6            No                   77.0          7.5
316            2.4           Yes                   86.0          6.8
317            1.3            No                   61.9          6.5

    diet_quality  exercise_frequency parental_education_level  \
0           Fair                   6                   Master
1           Poor                   4                   Master
2           Good                   5                 Bachelor
3           Poor                   3              High School
4           Poor                   0              High School
..           ...                 ...                      ...
313         Fair                   2                   Master
314         Fair                   4                 Bachelor
315         Fair                   2              High School
316         Poor                   1              High School
317         Good                   5                 Bachelor

    internet_quality  mental_health_rating extracurricular_participation  \
0            Average                     8                           Yes
1               Good                     1                           Yes
2               Good                    10                           Yes
3               Poor                     8                           Yes
4            Average                     1                           Yes
..               ...                   ...                           ...
313             Good                     3                           Yes
314          Average                     8                           Yes
315             Good                     6                           Yes
316          Average                     6                           Yes
317             Good                     9                           Yes

     exam_score
0          56.2
1          26.8
2         100.0
3          55.2
4          70.8
..          ...
313        80.9
314        72.5
315        76.1
316        65.9
317        64.4

[318 rows x 16 columns]