### Pandas
pandas a python library that is extensively used for data analytics, ML and other Data fields  
It provides possibility to organise data into something called Dataframe, which acts as a table of data (2D)  
It is organised into rows and columns with named indices

In [2]:
import pandas as pd

In [3]:
# Create a data frame using the pandas function
DF = pd.DataFrame ({
                    'Name' : ['Vishnu', "Ram", 'Bharat'], 
                    'Id' : [234, 201, 78],
                    'Course' : ['ML', 'GenAI', "Python"],
                    'Batch' : ['C1', 'C2', 'C1']})
DF

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
1     Ram  201   GenAI    C2
2  Bharat   78  Python    C1

In [4]:
# Let us understand how is it organised
print ("Data type : \n", DF.dtypes)

print ("Index : \n", DF.index)

print ("Number of Records : \n", len(DF))

print ("Number of Fields : \n", len(DF.columns))

Data type :
 Name        str
Id        int64
Course      str
Batch       str
dtype: object
Index :
 RangeIndex(start=0, stop=3, step=1)
Number of Records :
 3
Number of Fields :
 4

In [5]:
# Access specific Column
Names = DF['Name']

print ("Type : \n", type (Names))
print ("Content : \n",  Names)

Type :
 <class 'pandas.Series'>
Content :
 0    Vishnu
1       Ram
2    Bharat
Name: Name, dtype: str

In [6]:
# Access specific Row
Rec_1 = DF.iloc [1] # Access a row based on the index position

print ("Type : \n", type (Rec_1))
print ("Content : \n",  Rec_1)

Type :
 <class 'pandas.Series'>
Content :
 Name        Ram
Id          201
Course    GenAI
Batch        C2
Name: 1, dtype: object

In [7]:
# Make specific Column in a data frame
Names = DF[['Name']]

print ("Type : \n", type (Names))
print ("Content : \n",  Names)

Type :
 <class 'pandas.DataFrame'>
Content :
      Name
0  Vishnu
1     Ram
2  Bharat

In [8]:
# Filter out rows based on condition
Filtered = DF[DF['Batch'] == 'C1']
Filtered

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
2  Bharat   78  Python    C1

In [9]:
# Update an exising column values : just an assignment
DF['Id'] = [145, 156, 88]
DF

     Name   Id  Course Batch
0  Vishnu  145      ML    C1
1     Ram  156   GenAI    C2
2  Bharat   88  Python    C1

In [10]:
# Add another column, again just like a variable assignment
DF ['Score'] = [78, 85, 80]
DF

     Name   Id  Course Batch  Score
0  Vishnu  145      ML    C1     78
1     Ram  156   GenAI    C2     85
2  Bharat   88  Python    C1     80

In [11]:
# Add Rows by concatenating
new_rec = pd.DataFrame ({
                        'Name' : ['Dileep', 'Phani'],
                        'Id' : [101, 102],
                        'Course' : ['GenAI', 'ML'],
                        'Batch' : ['C1', 'C2'],
                        'Score' : [80, 75]
})
new_rec

     Name   Id Course Batch  Score
0  Dileep  101  GenAI    C1     80
1   Phani  102     ML    C2     75

In [12]:
DF = pd.concat ([DF, new_rec], ignore_index=True)
DF

     Name   Id  Course Batch  Score
0  Vishnu  145      ML    C1     78
1     Ram  156   GenAI    C2     85
2  Bharat   88  Python    C1     80
3  Dileep  101   GenAI    C1     80
4   Phani  102      ML    C2     75

In [13]:
# Aggregating functions. See how the column is accessed
print ("Min Score : ", DF.Score.min())
print ("Max Score : ", DF.Score.max())
print ("Mean Score : ", DF.Score.mean())
print ("Median Score : ", DF.Score.median())

Min Score :  75
Max Score :  85
Mean Score :  79.6
Median Score :  80.0

In [14]:
# Check the Max score per course : Use Group by
grp = DF.groupby ('Course') ['Score'].max ().rename ("Max ")
grp

Course
GenAI     85
ML        78
Python    80
Name: Max , dtype: int64

In [15]:
# Read data from a CSV file into Data Frame
Bhav_Copy = pd.read_csv ('sec_bhavdata_full_10032025.csv')
print (Bhav_Copy.dtypes)

SYMBOL                str
 SERIES               str
 DATE1                str
 PREV_CLOSE       float64
 OPEN_PRICE       float64
 HIGH_PRICE       float64
 LOW_PRICE        float64
 LAST_PRICE       float64
 CLOSE_PRICE      float64
 AVG_PRICE        float64
 TTL_TRD_QNTY       int64
 TURNOVER_LACS    float64
 NO_OF_TRADES       int64
 DELIV_QTY            str
 DELIV_PER            str
dtype: object

In [16]:
# Clean the column name to remove the leading spaces
Col = Bhav_Copy.columns
Bhav_Copy.columns = [C.strip() for C in Col]

In [17]:
# Change the Date field to datetime type
Bhav_Copy['DATE1'] = pd.to_datetime(Bhav_Copy['DATE1'])
print (Bhav_Copy.dtypes)
Bhav_Copy

SYMBOL                      str
SERIES                      str
DATE1            datetime64[us]
PREV_CLOSE              float64
OPEN_PRICE              float64
HIGH_PRICE              float64
LOW_PRICE               float64
LAST_PRICE              float64
CLOSE_PRICE             float64
AVG_PRICE               float64
TTL_TRD_QNTY              int64
TURNOVER_LACS           float64
NO_OF_TRADES              int64
DELIV_QTY                   str
DELIV_PER                   str
dtype: object

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,1018GS2026,GS,2025-03-10,109.51,109.51,109.90,109.51,109.90,109.90,109.90,180,0.20,2,180,100.00
1,20MICRONS,EQ,2025-03-10,204.33,203.00,218.00,201.00,205.00,204.27,209.62,159993,335.37,4397,67929,42.46
2,21STCENMGM,BE,2025-03-10,68.05,69.00,69.00,66.70,66.70,67.57,68.85,2189,1.51,32,-,-
3,360ONE,EQ,2025-03-10,972.90,972.00,984.00,890.00,894.00,895.40,909.66,2325435,21153.58,114801,1092193,46.97
4,3IINFOLTD,EQ,2025-03-10,24.45,24.41,24.75,23.20,23.44,23.46,23.79,610088,145.16,2389,426404,69.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,ZTECH,ST,2025-03-10,578.70,597.00,601.00,549.80,549.80,549.80,585.69,27900,163.41,83,25800,92.47
2850,ZUARI,EQ,2025-03-10,192.72,192.75,195.00,184.00,184.05,185.74,188.76,119175,224.95,3247,65357,54.84
2851,ZUARIIND,EQ,2025-03-10,253.93,253.00,257.59,241.30,242.00,242.64,249.24,40886,101.90,1177,27157,66.42
2852,ZYDUSLIFE,EQ,2025-03-10,900.80,900.80,911.15,890.00,891.40,893.70,900.86,605996,5459.16,34396,259745,42.86
2853,ZYDUSWELL,EQ,2025-03-10,1607.25,1617.95,1644.95,1590.25,1590.25,1614.60,1615.87,33725,544.95,7596,14346,42.54

In [18]:
# Filter out the Symbols where series is EQ and CLOSE_PRICE > 1000
filtered = Bhav_Copy.loc [(Bhav_Copy['CLOSE_PRICE'] >= 1000.0) & (Bhav_Copy['SERIES'] == ' EQ'), ['SYMBOL', 'CLOSE_PRICE']]
filtered

          SYMBOL  CLOSE_PRICE
5        3MINDIA     27468.15
65         AAVAS      1752.35
67           ABB      5160.30
68    ABBOTINDIA     30629.60
77         ABREL      1909.30
...          ...          ...
2822   XPROINDIA      1105.25
2825       YASHO      1775.90
2842      ZENTEC      1192.25
2843   ZFCVINDIA     11285.90
2853   ZYDUSWELL      1614.60

[368 rows x 2 columns]